FROM node:16-alpine3.15 as js-builder

ENV NODE_OPTIONS=--max_old_space_size=8000

WORKDIR /usr/src/app/

COPY package.json yarn.lock ./
COPY packages packages
COPY .yarnrc.yml ./
COPY .yarn .yarn
COPY plugins-bundled plugins-bundled

RUN npm config set registry https://registry.npm.taobao.org

RUN npm config set disturl https://npm.taobao.org/dist

RUN npm config rm proxy

RUN npm config rm https-proxy

RUN npm config set sass-binary-site http://npm.taobao.org/mirrors/node-sass

RUN yarn cache clean

RUN yarn set version 3.2.2

RUN yarn install

# Build image
# docker build --network=host -t grafana-cache:v1.0.0 -f Dockerfile.ubuntu.cache . --no-cache
